version: '3.8'

services:
  app:
    build: .
    container_name: online-store-sber-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE  # H2 in-memory DB
      SPRING_DATASOURCE_DRIVER_CLASSNAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.H2Dialect
      SPRING_H2_CONSOLE_ENABLED: "true"  # Включение консоли H2 для проверки данных
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge